# Generated by Django 4.2.4 on 2023-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('Ninth', 'Ninth'), ('Tenth', 'Tenth'), ('Eleventh', 'Eleventh'), ('Twelfth', 'Twelfth')], max_length=10)),
            ],
        ),
    ]
